/*
 * i2c_defines_poweramp.h
 *
 *  Created on: Oct 15, 2024
 *      Author: Alex
 *
 *  Power Amp Controller I2C register definitions
 *
 *  Register map:
 *  * General registers
 *    - 0x01: STATUS: General status (1B, bit field, r)
 *    - 0x08: CONTROL: General control (1B, bit field, rw)
 *  * Interrupt registers
 *    - 0x10: INT_MASK: Interrupt mask (1B, bit field, rw, high = interrupt enable)
 *    - 0x11: INT_FLAGS: Interrupt flags (1B, bit field, rc, high = interrupt occurred)
 *  * PVDD registers
 *    - 0x20: PVDD_REQ: PVDD requested voltage (4B, float little endian, rw)
 *    - 0x21: PVDD_MEASURED: PVDD measured voltage (4B, float little endian, r)
 *    - 0x22: PVDD_OFFSET: PVDD request offset (4B, float little endian, r)
 *  * Output monitor registers
 *    - 0x30-0x33: MON_VRMS_FAST_[A-D]: Channel A-D rms voltage, 0.1s time constant (each 4B, float little endian, r)
 *    - 0x34-0x37: MON_IRMS_FAST_[A-D]: Channel A-D rms current, 0.1s time constant (each 4B, float little endian, r)
 *    - 0x38-0x3B: MON_PAVG_FAST_[A-D]: Channel A-D avg real power, 0.1s time constant (each 4B, float little endian, r)
 *    - 0x3C-0x3F: MON_PAPP_FAST_[A-D]: Channel A-D avg apparent power, 0.1s time constant (each 4B, float little endian, r)
 *    - 0x40-0x43: MON_VRMS_SLOW_[A-D]: Channel A-D rms voltage, 1s time constant (each 4B, float little endian, r)
 *    - 0x44-0x47: MON_IRMS_SLOW_[A-D]: Channel A-D rms current, 1s time constant (each 4B, float little endian, r)
 *    - 0x48-0x4B: MON_PAVG_SLOW_[A-D]: Channel A-D avg real power, 1s time constant (each 4B, float little endian, r)
 *    - 0x4C-0x4F: MON_PAPP_SLOW_[A-D]: Channel A-D avg apparent power, 1s time constant (each 4B, float little endian, r)
 *  * Safety system registers - threshold writes only permitted during manual shutdown
 *    - 0x50-0x54: SERR_IRMS_INST_[A-D,SUM]: Channel A-D and sum current error threshold, instantaneous (each 4B, float little endian, rw)
 *    - 0x55-0x59: SERR_IRMS_FAST_[A-D,SUM]: Channel A-D and sum current error threshold, 0.1s time constant (each 4B, float little endian, rw)
 *    - 0x5A-0x5E: SERR_IRMS_SLOW_[A-D,SUM]: Channel A-D and sum current error threshold, 1s time constant (each 4B, float little endian, rw)
 *    - 0x60-0x64: SERR_PAVG_INST_[A-D,SUM]: Channel A-D and sum real power error threshold, instantaneous (each 4B, float little endian, rw)
 *    - 0x65-0x69: SERR_PAVG_FAST_[A-D,SUM]: Channel A-D and sum real power error threshold, 0.1s time constant (each 4B, float little endian, rw)
 *    - 0x6A-0x6E: SERR_PAVG_SLOW_[A-D,SUM]: Channel A-D and sum real power error threshold, 1s time constant (each 4B, float little endian, rw)
 *    - 0x70-0x74: SERR_PAPP_INST_[A-D,SUM]: Channel A-D and sum apparent power error threshold, instantaneous (each 4B, float little endian, rw)
 *    - 0x75-0x79: SERR_PAPP_FAST_[A-D,SUM]: Channel A-D and sum apparent power error threshold, 0.1s time constant (each 4B, float little endian, rw)
 *    - 0x7A-0x7E: SERR_PAPP_SLOW_[A-D,SUM]: Channel A-D and sum apparent power error threshold, 1s time constant (each 4B, float little endian, rw)
 *    - 0x80-0x84: SWARN_IRMS_INST_[A-D,SUM]: Channel A-D and sum current warning threshold, instantaneous (each 4B, float little endian, rw)
 *    - 0x85-0x89: SWARN_IRMS_FAST_[A-D,SUM]: Channel A-D and sum current warning threshold, 0.1s time constant (each 4B, float little endian, rw)
 *    - 0x8A-0x8E: SWARN_IRMS_SLOW_[A-D,SUM]: Channel A-D and sum current warning threshold, 1s time constant (each 4B, float little endian, rw)
 *    - 0x90-0x94: SWARN_PAVG_INST_[A-D,SUM]: Channel A-D and sum real power warning threshold, instantaneous (each 4B, float little endian, rw)
 *    - 0x95-0x99: SWARN_PAVG_FAST_[A-D,SUM]: Channel A-D and sum real power warning threshold, 0.1s time constant (each 4B, float little endian, rw)
 *    - 0x9A-0x9E: SWARN_PAVG_SLOW_[A-D,SUM]: Channel A-D and sum real power warning threshold, 1s time constant (each 4B, float little endian, rw)
 *    - 0xA0-0xA4: SWARN_PAPP_INST_[A-D,SUM]: Channel A-D and sum apparent power warning threshold, instantaneous (each 4B, float little endian, rw)
 *    - 0xA5-0xA9: SWARN_PAPP_FAST_[A-D,SUM]: Channel A-D and sum apparent power warning threshold, 0.1s time constant (each 4B, float little endian, rw)
 *    - 0xAA-0xAE: SWARN_PAPP_SLOW_[A-D,SUM]: Channel A-D and sum apparent power warning threshold, 1s time constant (each 4B, float little endian, rw)
 *    - 0xB0: SAFETY_STATUS: Status of safety system (1B, bit field, r)
 *    - 0xB1: SERR_SOURCE: Indication of error source (2B, bit field, r)
 *    - 0xB2: SWARN_SOURCE: Indication of warning source (2B, bit field, r)
 *  * Misc registers
 *    - 0xFF: MODULE_ID: Module ID (1B, hex, r)
 *
 *  Bit field definitions:
 *  * STATUS (0x01, 1B):
 *    - 7: I2CERR: I2C communication error detected since last STATUS read
 *    - 6: SWARN: safety warning active (any)
 *    - 5: PVDD_OLIM: PVDD offset at limit
 *    - 4: PVDD_ONZ: PVDD offset nonzero
 *    - 3: PVDD_VALID: PVDD voltage valid
 *    - 2: AMP_SD: amplifier shutdown active (set by this controller, external shutdown is possible through header and will not be detected)
 *    - 1: AMP_CLIPOTW: amplifier clip/otw active
 *    - 0: AMP_FAULT: amplifier fault active
 *  * CONTROL (0x08, 1B):
 *    - 4-7: RESET: controller reset (write 0xA to trigger software reset)
 *    - 1: INT_EN: enable interrupts
 *    - 0: AMP_MAN_SD: activate manual amp shutdown
 *  * INT_MASK (0x10, 1B):
 *    - 4: INT_PVDD_OLIM: PVDD offset at limit
 *    - 3: INT_PVDD_ERR: PVDD voltage error
 *    - 2: INT_SWARN: safety warning
 *    - 1: INT_SERR: safety error shutdown
 *    - 0: INT_AMP_FAULT: amplifier fault
 *  * INT_FLAGS (0x11, 1B):
 *    same layout as INT_MASK
 *  * SAFETY_STATUS (0xB0, 1B):
 *    - 1: MAN_SD: manual shutdown active
 *    - 0: SERR_SD: safety shutdown active
 *  * SERR_SOURCE (0xB1, 2B):
 *    - 13-5: MTYPE: source measurement type (one-hot, high to low: IRMS inst/fast/slow, PAVG inst/fast/slow, PAPP inst/fast/slow)
 *    - 4-0: CHAN: source channel (one-hot, high to low: A,B,C,D,Sum)
 *  * SWARN_SOURCE (0xB2, 2B):
 *    same layout as SERR_SOURCE
 */

#ifndef INC_I2C_DEFINES_POWERAMP_H_
#define INC_I2C_DEFINES_POWERAMP_H_


//virtual register sizes in bytes - 0 means register is invalid
#define I2CDEF_POWERAMP_REG_SIZES {\
  0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,\
  1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\
  4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,\
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,\
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0,\
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0,\
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0,\
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0,\
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0,\
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0,\
  1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }


//General registers
#define I2CDEF_POWERAMP_STATUS 0x01

#define I2CDEF_POWERAMP_STATUS_AMP_FAULT_Pos 0
#define I2CDEF_POWERAMP_STATUS_AMP_FAULT_Msk (0x1 << I2CDEF_POWERAMP_STATUS_AMP_FAULT_Pos)
#define I2CDEF_POWERAMP_STATUS_AMP_CLIPOTW_Pos 1
#define I2CDEF_POWERAMP_STATUS_AMP_CLIPOTW_Msk (0x1 << I2CDEF_POWERAMP_STATUS_AMP_CLIPOTW_Pos)
#define I2CDEF_POWERAMP_STATUS_AMP_SD_Pos 2
#define I2CDEF_POWERAMP_STATUS_AMP_SD_Msk (0x1 << I2CDEF_POWERAMP_STATUS_AMP_SD_Pos)
#define I2CDEF_POWERAMP_STATUS_PVDD_VALID_Pos 3
#define I2CDEF_POWERAMP_STATUS_PVDD_VALID_Msk (0x1 << I2CDEF_POWERAMP_STATUS_PVDD_VALID_Pos)
#define I2CDEF_POWERAMP_STATUS_PVDD_ONZ_Pos 4
#define I2CDEF_POWERAMP_STATUS_PVDD_ONZ_Msk (0x1 << I2CDEF_POWERAMP_STATUS_PVDD_ONZ_Pos)
#define I2CDEF_POWERAMP_STATUS_PVDD_OLIM_Pos 5
#define I2CDEF_POWERAMP_STATUS_PVDD_OLIM_Msk (0x1 << I2CDEF_POWERAMP_STATUS_PVDD_OLIM_Pos)
#define I2CDEF_POWERAMP_STATUS_SWARN_Pos 6
#define I2CDEF_POWERAMP_STATUS_SWARN_Msk (0x1 << I2CDEF_POWERAMP_STATUS_SWARN_Pos)
#define I2CDEF_POWERAMP_STATUS_I2CERR_Pos 7
#define I2CDEF_POWERAMP_STATUS_I2CERR_Msk (0x1 << I2CDEF_POWERAMP_STATUS_I2CERR_Pos)

#define I2CDEF_POWERAMP_CONTROL 0x08

#define I2CDEF_POWERAMP_CONTROL_AMP_MAN_SD_Pos 0
#define I2CDEF_POWERAMP_CONTROL_AMP_MAN_SD_Msk (0x1 << I2CDEF_POWERAMP_CONTROL_AMP_MAN_SD_Pos)
#define I2CDEF_POWERAMP_CONTROL_INT_EN_Pos 1
#define I2CDEF_POWERAMP_CONTROL_INT_EN_Msk (0x1 << I2CDEF_POWERAMP_CONTROL_INT_EN_Pos)
#define I2CDEF_POWERAMP_CONTROL_RESET_Pos 4
#define I2CDEF_POWERAMP_CONTROL_RESET_Msk (0xF << I2CDEF_POWERAMP_CONTROL_RESET_Pos)
#define I2CDEF_POWERAMP_CONTROL_RESET_VALUE 0xA


//Interrupt registers
#define I2CDEF_POWERAMP_INT_MASK 0x10

#define I2CDEF_POWERAMP_INT_MASK_INT_AMP_FAULT_Pos 0
#define I2CDEF_POWERAMP_INT_MASK_INT_AMP_FAULT_Msk (0x1 << I2CDEF_POWERAMP_INT_MASK_INT_AMP_FAULT_Pos)
#define I2CDEF_POWERAMP_INT_MASK_INT_SERR_Pos 1
#define I2CDEF_POWERAMP_INT_MASK_INT_SERR_Msk (0x1 << I2CDEF_POWERAMP_INT_MASK_INT_SERR_Pos)
#define I2CDEF_POWERAMP_INT_MASK_INT_SWARN_Pos 2
#define I2CDEF_POWERAMP_INT_MASK_INT_SWARN_Msk (0x1 << I2CDEF_POWERAMP_INT_MASK_INT_SWARN_Pos)
#define I2CDEF_POWERAMP_INT_MASK_INT_PVDD_ERR_Pos 3
#define I2CDEF_POWERAMP_INT_MASK_INT_PVDD_ERR_Msk (0x1 << I2CDEF_POWERAMP_INT_MASK_INT_PVDD_ERR_Pos)
#define I2CDEF_POWERAMP_INT_MASK_INT_PVDD_OLIM_Pos 4
#define I2CDEF_POWERAMP_INT_MASK_INT_PVDD_OLIM_Msk (0x1 << I2CDEF_POWERAMP_INT_MASK_INT_PVDD_OLIM_Pos)

#define I2CDEF_POWERAMP_INT_FLAGS 0x11

#define I2CDEF_POWERAMP_INT_FLAGS_INT_AMP_FAULT_Pos I2CDEF_POWERAMP_INT_MASK_INT_AMP_FAULT_Pos
#define I2CDEF_POWERAMP_INT_FLAGS_INT_AMP_FAULT_Msk I2CDEF_POWERAMP_INT_MASK_INT_AMP_FAULT_Msk
#define I2CDEF_POWERAMP_INT_FLAGS_INT_SERR_Pos I2CDEF_POWERAMP_INT_MASK_INT_SERR_Pos
#define I2CDEF_POWERAMP_INT_FLAGS_INT_SERR_Msk I2CDEF_POWERAMP_INT_MASK_INT_SERR_Msk
#define I2CDEF_POWERAMP_INT_FLAGS_INT_SWARN_Pos I2CDEF_POWERAMP_INT_MASK_INT_SWARN_Pos
#define I2CDEF_POWERAMP_INT_FLAGS_INT_SWARN_Msk I2CDEF_POWERAMP_INT_MASK_INT_SWARN_Msk
#define I2CDEF_POWERAMP_INT_FLAGS_INT_PVDD_ERR_Pos I2CDEF_POWERAMP_INT_MASK_INT_PVDD_ERR_Pos
#define I2CDEF_POWERAMP_INT_FLAGS_INT_PVDD_ERR_Msk I2CDEF_POWERAMP_INT_MASK_INT_PVDD_ERR_Msk
#define I2CDEF_POWERAMP_INT_FLAGS_INT_PVDD_OLIM_Pos I2CDEF_POWERAMP_INT_MASK_INT_PVDD_OLIM_Pos
#define I2CDEF_POWERAMP_INT_FLAGS_INT_PVDD_OLIM_Msk I2CDEF_POWERAMP_INT_MASK_INT_PVDD_OLIM_Msk


//PVDD registers
#define I2CDEF_POWERAMP_PVDD_REQ 0x20

#define I2CDEF_POWERAMP_PVDD_MEASURED 0x21

#define I2CDEF_POWERAMP_PVDD_OFFSET 0x22


//Output monitor registers
#define I2CDEF_POWERAMP_MON_VRMS_FAST_A 0x30
#define I2CDEF_POWERAMP_MON_VRMS_FAST_B 0x31
#define I2CDEF_POWERAMP_MON_VRMS_FAST_C 0x32
#define I2CDEF_POWERAMP_MON_VRMS_FAST_D 0x33

#define I2CDEF_POWERAMP_MON_IRMS_FAST_A 0x34
#define I2CDEF_POWERAMP_MON_IRMS_FAST_B 0x35
#define I2CDEF_POWERAMP_MON_IRMS_FAST_C 0x36
#define I2CDEF_POWERAMP_MON_IRMS_FAST_D 0x37

#define I2CDEF_POWERAMP_MON_PAVG_FAST_A 0x38
#define I2CDEF_POWERAMP_MON_PAVG_FAST_B 0x39
#define I2CDEF_POWERAMP_MON_PAVG_FAST_C 0x3A
#define I2CDEF_POWERAMP_MON_PAVG_FAST_D 0x3B

#define I2CDEF_POWERAMP_MON_PAPP_FAST_A 0x3C
#define I2CDEF_POWERAMP_MON_PAPP_FAST_B 0x3D
#define I2CDEF_POWERAMP_MON_PAPP_FAST_C 0x3E
#define I2CDEF_POWERAMP_MON_PAPP_FAST_D 0x3F

#define I2CDEF_POWERAMP_MON_VRMS_SLOW_A 0x40
#define I2CDEF_POWERAMP_MON_VRMS_SLOW_B 0x41
#define I2CDEF_POWERAMP_MON_VRMS_SLOW_C 0x42
#define I2CDEF_POWERAMP_MON_VRMS_SLOW_D 0x43

#define I2CDEF_POWERAMP_MON_IRMS_SLOW_A 0x44
#define I2CDEF_POWERAMP_MON_IRMS_SLOW_B 0x45
#define I2CDEF_POWERAMP_MON_IRMS_SLOW_C 0x46
#define I2CDEF_POWERAMP_MON_IRMS_SLOW_D 0x47

#define I2CDEF_POWERAMP_MON_PAVG_SLOW_A 0x48
#define I2CDEF_POWERAMP_MON_PAVG_SLOW_B 0x49
#define I2CDEF_POWERAMP_MON_PAVG_SLOW_C 0x4A
#define I2CDEF_POWERAMP_MON_PAVG_SLOW_D 0x4B

#define I2CDEF_POWERAMP_MON_PAPP_SLOW_A 0x4C
#define I2CDEF_POWERAMP_MON_PAPP_SLOW_B 0x4D
#define I2CDEF_POWERAMP_MON_PAPP_SLOW_C 0x4E
#define I2CDEF_POWERAMP_MON_PAPP_SLOW_D 0x4F


//Safety system registers
#define I2CDEF_POWERAMP_SERR_IRMS_INST_A 0x50
#define I2CDEF_POWERAMP_SERR_IRMS_INST_B 0x51
#define I2CDEF_POWERAMP_SERR_IRMS_INST_C 0x52
#define I2CDEF_POWERAMP_SERR_IRMS_INST_D 0x53
#define I2CDEF_POWERAMP_SERR_IRMS_INST_SUM 0x54

#define I2CDEF_POWERAMP_SERR_IRMS_FAST_A 0x55
#define I2CDEF_POWERAMP_SERR_IRMS_FAST_B 0x56
#define I2CDEF_POWERAMP_SERR_IRMS_FAST_C 0x57
#define I2CDEF_POWERAMP_SERR_IRMS_FAST_D 0x58
#define I2CDEF_POWERAMP_SERR_IRMS_FAST_SUM 0x59

#define I2CDEF_POWERAMP_SERR_IRMS_SLOW_A 0x5A
#define I2CDEF_POWERAMP_SERR_IRMS_SLOW_B 0x5B
#define I2CDEF_POWERAMP_SERR_IRMS_SLOW_C 0x5C
#define I2CDEF_POWERAMP_SERR_IRMS_SLOW_D 0x5D
#define I2CDEF_POWERAMP_SERR_IRMS_SLOW_SUM 0x5E

#define I2CDEF_POWERAMP_SERR_PAVG_INST_A 0x60
#define I2CDEF_POWERAMP_SERR_PAVG_INST_B 0x61
#define I2CDEF_POWERAMP_SERR_PAVG_INST_C 0x62
#define I2CDEF_POWERAMP_SERR_PAVG_INST_D 0x63
#define I2CDEF_POWERAMP_SERR_PAVG_INST_SUM 0x64

#define I2CDEF_POWERAMP_SERR_PAVG_FAST_A 0x65
#define I2CDEF_POWERAMP_SERR_PAVG_FAST_B 0x66
#define I2CDEF_POWERAMP_SERR_PAVG_FAST_C 0x67
#define I2CDEF_POWERAMP_SERR_PAVG_FAST_D 0x68
#define I2CDEF_POWERAMP_SERR_PAVG_FAST_SUM 0x69

#define I2CDEF_POWERAMP_SERR_PAVG_SLOW_A 0x6A
#define I2CDEF_POWERAMP_SERR_PAVG_SLOW_B 0x6B
#define I2CDEF_POWERAMP_SERR_PAVG_SLOW_C 0x6C
#define I2CDEF_POWERAMP_SERR_PAVG_SLOW_D 0x6D
#define I2CDEF_POWERAMP_SERR_PAVG_SLOW_SUM 0x6E

#define I2CDEF_POWERAMP_SERR_PAPP_INST_A 0x70
#define I2CDEF_POWERAMP_SERR_PAPP_INST_B 0x71
#define I2CDEF_POWERAMP_SERR_PAPP_INST_C 0x72
#define I2CDEF_POWERAMP_SERR_PAPP_INST_D 0x73
#define I2CDEF_POWERAMP_SERR_PAPP_INST_SUM 0x74

#define I2CDEF_POWERAMP_SERR_PAPP_FAST_A 0x75
#define I2CDEF_POWERAMP_SERR_PAPP_FAST_B 0x76
#define I2CDEF_POWERAMP_SERR_PAPP_FAST_C 0x77
#define I2CDEF_POWERAMP_SERR_PAPP_FAST_D 0x78
#define I2CDEF_POWERAMP_SERR_PAPP_FAST_SUM 0x79

#define I2CDEF_POWERAMP_SERR_PAPP_SLOW_A 0x7A
#define I2CDEF_POWERAMP_SERR_PAPP_SLOW_B 0x7B
#define I2CDEF_POWERAMP_SERR_PAPP_SLOW_C 0x7C
#define I2CDEF_POWERAMP_SERR_PAPP_SLOW_D 0x7D
#define I2CDEF_POWERAMP_SERR_PAPP_SLOW_SUM 0x7E

#define I2CDEF_POWERAMP_SWARN_IRMS_INST_A 0x80
#define I2CDEF_POWERAMP_SWARN_IRMS_INST_B 0x81
#define I2CDEF_POWERAMP_SWARN_IRMS_INST_C 0x82
#define I2CDEF_POWERAMP_SWARN_IRMS_INST_D 0x83
#define I2CDEF_POWERAMP_SWARN_IRMS_INST_SUM 0x84

#define I2CDEF_POWERAMP_SWARN_IRMS_FAST_A 0x85
#define I2CDEF_POWERAMP_SWARN_IRMS_FAST_B 0x86
#define I2CDEF_POWERAMP_SWARN_IRMS_FAST_C 0x87
#define I2CDEF_POWERAMP_SWARN_IRMS_FAST_D 0x88
#define I2CDEF_POWERAMP_SWARN_IRMS_FAST_SUM 0x89

#define I2CDEF_POWERAMP_SWARN_IRMS_SLOW_A 0x8A
#define I2CDEF_POWERAMP_SWARN_IRMS_SLOW_B 0x8B
#define I2CDEF_POWERAMP_SWARN_IRMS_SLOW_C 0x8C
#define I2CDEF_POWERAMP_SWARN_IRMS_SLOW_D 0x8D
#define I2CDEF_POWERAMP_SWARN_IRMS_SLOW_SUM 0x8E

#define I2CDEF_POWERAMP_SWARN_PAVG_INST_A 0x90
#define I2CDEF_POWERAMP_SWARN_PAVG_INST_B 0x91
#define I2CDEF_POWERAMP_SWARN_PAVG_INST_C 0x92
#define I2CDEF_POWERAMP_SWARN_PAVG_INST_D 0x93
#define I2CDEF_POWERAMP_SWARN_PAVG_INST_SUM 0x94

#define I2CDEF_POWERAMP_SWARN_PAVG_FAST_A 0x95
#define I2CDEF_POWERAMP_SWARN_PAVG_FAST_B 0x96
#define I2CDEF_POWERAMP_SWARN_PAVG_FAST_C 0x97
#define I2CDEF_POWERAMP_SWARN_PAVG_FAST_D 0x98
#define I2CDEF_POWERAMP_SWARN_PAVG_FAST_SUM 0x99

#define I2CDEF_POWERAMP_SWARN_PAVG_SLOW_A 0x9A
#define I2CDEF_POWERAMP_SWARN_PAVG_SLOW_B 0x9B
#define I2CDEF_POWERAMP_SWARN_PAVG_SLOW_C 0x9C
#define I2CDEF_POWERAMP_SWARN_PAVG_SLOW_D 0x9D
#define I2CDEF_POWERAMP_SWARN_PAVG_SLOW_SUM 0x9E

#define I2CDEF_POWERAMP_SWARN_PAPP_INST_A 0xA0
#define I2CDEF_POWERAMP_SWARN_PAPP_INST_B 0xA1
#define I2CDEF_POWERAMP_SWARN_PAPP_INST_C 0xA2
#define I2CDEF_POWERAMP_SWARN_PAPP_INST_D 0xA3
#define I2CDEF_POWERAMP_SWARN_PAPP_INST_SUM 0xA4

#define I2CDEF_POWERAMP_SWARN_PAPP_FAST_A 0xA5
#define I2CDEF_POWERAMP_SWARN_PAPP_FAST_B 0xA6
#define I2CDEF_POWERAMP_SWARN_PAPP_FAST_C 0xA7
#define I2CDEF_POWERAMP_SWARN_PAPP_FAST_D 0xA8
#define I2CDEF_POWERAMP_SWARN_PAPP_FAST_SUM 0xA9

#define I2CDEF_POWERAMP_SWARN_PAPP_SLOW_A 0xAA
#define I2CDEF_POWERAMP_SWARN_PAPP_SLOW_B 0xAB
#define I2CDEF_POWERAMP_SWARN_PAPP_SLOW_C 0xAC
#define I2CDEF_POWERAMP_SWARN_PAPP_SLOW_D 0xAD
#define I2CDEF_POWERAMP_SWARN_PAPP_SLOW_SUM 0xAE

#define I2CDEF_POWERAMP_SAFETY_STATUS 0xB0

#define I2CDEF_POWERAMP_SAFETY_STATUS_SAFETY_SERR_SD_Pos 0
#define I2CDEF_POWERAMP_SAFETY_STATUS_SAFETY_SERR_SD_Msk (0x1 << I2CDEF_POWERAMP_SAFETY_STATUS_SAFETY_SERR_SD_Pos)
#define I2CDEF_POWERAMP_SAFETY_STATUS_SAFETY_MAN_SD_Pos 1
#define I2CDEF_POWERAMP_SAFETY_STATUS_SAFETY_MAN_SD_Msk (0x1 << I2CDEF_POWERAMP_SAFETY_STATUS_SAFETY_MAN_SD_Pos)

#define I2CDEF_POWERAMP_SERR_SOURCE 0xB1

#define I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Pos 0
#define I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Msk (0x1F << I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_CHAN_A (0x10 << I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_CHAN_B (0x08 << I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_CHAN_C (0x04 << I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_CHAN_D (0x02 << I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_CHAN_SUM (0x01 << I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos 5
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Msk (0x1FF << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_IRMS_INST (0x100 << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_IRMS_FAST (0x080 << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_IRMS_SLOW (0x040 << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAVG_INST (0x020 << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAVG_FAST (0x010 << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAVG_SLOW (0x008 << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAPP_INST (0x004 << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAPP_FAST (0x002 << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)
#define I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAPP_SLOW (0x001 << I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos)

#define I2CDEF_POWERAMP_SWARN_SOURCE 0xB2

#define I2CDEF_POWERAMP_SWARN_SOURCE_CHAN_Pos I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Pos
#define I2CDEF_POWERAMP_SWARN_SOURCE_CHAN_Msk I2CDEF_POWERAMP_SERR_SOURCE_CHAN_Msk
#define I2CDEF_POWERAMP_SWARN_SOURCE_CHAN_A I2CDEF_POWERAMP_SERR_SOURCE_CHAN_A
#define I2CDEF_POWERAMP_SWARN_SOURCE_CHAN_B I2CDEF_POWERAMP_SERR_SOURCE_CHAN_B
#define I2CDEF_POWERAMP_SWARN_SOURCE_CHAN_C I2CDEF_POWERAMP_SERR_SOURCE_CHAN_C
#define I2CDEF_POWERAMP_SWARN_SOURCE_CHAN_D I2CDEF_POWERAMP_SERR_SOURCE_CHAN_D
#define I2CDEF_POWERAMP_SWARN_SOURCE_CHAN_SUM I2CDEF_POWERAMP_SERR_SOURCE_CHAN_SUM
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_Pos I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Pos
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_Msk I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_Msk
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_IRMS_INST I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_IRMS_INST
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_IRMS_FAST I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_IRMS_FAST
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_IRMS_SLOW I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_IRMS_SLOW
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_PAVG_INST I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAVG_INST
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_PAVG_FAST I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAVG_FAST
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_PAVG_SLOW I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAVG_SLOW
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_PAPP_INST I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAPP_INST
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_PAPP_FAST I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAPP_FAST
#define I2CDEF_POWERAMP_SWARN_SOURCE_MTYPE_PAPP_SLOW I2CDEF_POWERAMP_SERR_SOURCE_MTYPE_PAPP_SLOW


//Misc registers
#define I2CDEF_POWERAMP_MODULE_ID 0xFF
#define I2CDEF_POWERAMP_MODULE_ID_VALUE 0xA1


#endif /* INC_I2C_DEFINES_POWERAMP_H_ */
