M48
; DRILL file {KiCad 8.0.5} date 2025-01-05T11:13:20+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-05T11:13:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T1
X6.4016Y-4.5516
T2
X4.4843Y-3.3622
X4.4843Y-4.4409
X6.4094Y-4.0079
X7.0827Y-4.0079
M30
